# Copyright (c) 2024 Abel Kevin Ngaleu, University of Luxembourg
# This software is licensed under the MIT License.
# See the LICENSE file for more details.

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: dp_plugin
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
