from pymisp import MISPObject


def build_misp_object(misp_object: MISPObject, data) -> dict:
    misp_object.add_attribute(object_relation='minimumFcrClicks', type='text', value=data.get("minimumFcrClicks"))
    misp_object.add_attribute(object_relation='fcgPaths', type='text', value=data.get("fcgPaths"))
    misp_object.add_attribute(object_relation='fcrPaths', type='text', value=data.get("fcrPaths"))
    misp_object.add_attribute(object_relation='canNavigate', type='text', value=data.get("canNavigate"))
    misp_object.add_attribute(object_relation='fcgDuration', type='text', value=data.get("fcgDuration"))
    misp_object.add_attribute(object_relation='fcrDuration', type='text', value=data.get("fcrDuration"))
    misp_object.add_attribute(object_relation='acceptButtonSize', type='text', value=data.get("acceptButtonSize"))
    misp_object.add_attribute(object_relation='rejectButtonSize', type='text', value=data.get("rejectButtonSize"))
    misp_object.add_attribute(object_relation='optionButtonSize', type='text', value=data.get("optionButtonSize"))
    misp_object.add_attribute(object_relation='acceptButtonColor', type='text', value=data.get("acceptButtonColor"))
    misp_object.add_attribute(object_relation='rejectButtonColor', type='text', value=data.get("rejectButtonColor"))
    misp_object.add_attribute(object_relation='optionButtonColor', type='text', value=data.get("optionButtonColor"))
    misp_object.add_attribute(object_relation='textOfTheAcceptButton', type='text', value=data.get("textOfTheAcceptButton"))
    misp_object.add_attribute(object_relation='textOfTheRejectButton', type='text', value=data.get("textOfTheRejectButton"))
    misp_object.add_attribute(object_relation='textOfTheOptionButton', type='text', value=data.get("textOfTheOptionButton"))
    misp_object.add_attribute(object_relation='bannerSize', type='text', value=data.get("bannerSize"))
    misp_object.add_attribute(object_relation='hasCCImage', type='text', value=data.get("hasCCImage"))
    misp_object.add_attribute(object_relation='hasFCRIcon', type='text', value=data.get("hasFCRIcon"))
    misp_object.add_attribute(object_relation='hasFCGIcon', type='text', value=data.get("hasFCGIcon"))
    misp_object.add_attribute(object_relation='privacyPolicyLinkPresent', type='text', value=data.get("privacyPolicyLinkPresent"))
    misp_object.add_attribute(object_relation='availabilityOfFCGProcess', type='text', value=data.get("availabilityOfFCGProcess"))
    misp_object.add_attribute(object_relation='availabilityOfFCRProcess', type='text', value=data.get("availabilityOfFCRProcess"))
    misp_object.add_attribute(object_relation='fcgFontType', type='text', value=data.get("fcgFontType"))
    misp_object.add_attribute(object_relation='fcrFontType', type='text', value=data.get("fcrFontType"))
    misp_object.add_attribute(object_relation='fcgFontSize', type='text', value=data.get("fcgFontSize"))
    misp_object.add_attribute(object_relation='fcrFontSize', type='text', value=data.get("fcrFontSize"))
    misp_object.add_attribute(object_relation='fcgFontWeight', type='text', value=data.get("fcgFontWeight"))
    misp_object.add_attribute(object_relation='fcrFontWeight', type='text', value=data.get("fcrFontWeight"))
    misp_object.add_attribute(object_relation='bannerTextContent', type='text', value=data.get("bannerTextContent"))
    misp_object.add_attribute(object_relation='asymmetric', type='text', value=data.get("asymmetric"))
    misp_object.add_attribute(object_relation='restrictive', type='text', value=data.get("restrictive"))
    misp_object.add_attribute(object_relation='datetime', type='datetime', value=data.get("datetime"))
    misp_object.add_attribute(object_relation='covert', type='text', value=data.get("covert"))
    misp_object.add_attribute(object_relation='darkPattern', type='text', value=data.get("darkPattern"))
    misp_object.add_attribute(object_relation='deceptive', type='text', value=data.get("deceptive"))
    misp_object.add_attribute(object_relation='hiddenInformation', type='text', value=data.get("hiddenInformation"))
    misp_object.add_attribute(object_relation='covertRulesMatched', type='text', value=data.get("covertRulesMatched"))
    misp_object.add_attribute(object_relation='restrictiveRulesMatched', type='text', value=data.get("restrictiveRulesMatched"))
    misp_object.add_attribute(object_relation='asymmetricRulesMatched', type='text', value=data.get("asymmetricRulesMatched"))
    misp_object.add_attribute(object_relation='deceptiveRulesMatched', type='text', value=data.get("deceptiveRulesMatched"))
    misp_object.add_attribute(object_relation='hiddenInformationRulesMatched', type='text', value=data.get("hiddenInformationRulesMatched"))

    return misp_object